name: Generate PDFs from Markdown

on: [push]

jobs:
  generate_pdfs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install md2pdf
      run: |
        python -m pip install --upgrade pip
        pip install md2pdf

    - name: Delete old PDFs
      run: |
        if [ -d "pdf" ]; then
          rm -rf pdf
        fi

    - name: Generate new PDFs
      run: |
        for md_file in $(find . -name "*.md" | sed 's/ /\\ /g'); do
          pdf_dir="pdf/$(dirname "$md_file")"
          pdf_file="$pdf_dir/$(basename "$md_file" .md).pdf"
          mkdir -p "$pdf_dir"
          md2pdf "$md_file" "$pdf_file"
        done

    - name: Commit and push PDFs
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add pdf/
        git commit -m "Regenerate PDFs" || echo "No changes to commit"
        git push
