name: Generate PDFs from Markdown
on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  generate_pdfs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc wkhtmltopdf

    - name: Delete old PDFs
      run: |
        if [ -d "pdf" ]; then
          rm -rf pdf
        fi

    - name: Generate new PDFs
      run: |
        find . -name "*.md" | while IFS= read -r md_file; do
          md_file="${md_file#./}"

          sed -i 's/!\[\[\(.*\)\]\]/![\1](\1)/g' "$md_file"

          base_dir="$(dirname "$md_file")"
          pdf_dir="pdf/$base_dir"
          html_file="$base_dir/$(basename "$md_file" .md).html"
          pdf_file="$pdf_dir/$(basename "$md_file" .md).pdf"

          echo "Creating directory $pdf_dir"
          echo "PDF will be located at $pdf_file"
          echo "HTML file will be located at $html_file"
          mkdir -p "$pdf_dir"
          pandoc "$md_file" -s -t html5 --mathml -o "$html_file"
          wkhtmltopdf --enable-local-file-access "$html_file" "$pdf_file"
          rm "$html_file"
        done

    - name: Push to repo
      run: |
        git config --global user.email "kristian.zh.apostolov@gmail.com"
        git config --global user.name "Kristian Apostolov"
        git add -f pdf/*
        git commit -m "Generate PDFs"
        git push origin main

