name: Generate PDFs from Markdown

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Identify changed markdown files
      id: getfile
      run: |
        files=$(git diff --name-only HEAD^ HEAD | grep ".md$")
        echo "::set-output name=files::$files"

    - name: Set up Python
      if: steps.getfile.outputs.files != ''
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install pandoc
      if: steps.getfile.outputs.files != ''
      run: sudo apt-get install pandoc

    - name: Install Python dependencies
      if: steps.getfile.outputs.files != ''
      run: |
        pip install pypandoc

    - name: Convert MD to PDF
      if: steps.getfile.outputs.files != ''
      run: |
        IFS=" " read -ra FILES <<< "${{ steps.getfile.outputs.files }}"
        python script_name.py "${FILES[@]}"

    - name: Commit and push PDFs
      if: steps.getfile.outputs.files != ''
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "Add generated PDFs" || echo "No changes to commit"
        git push
