name: Generate PDFs from Markdown
on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  generate_pdfs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install md2pdf
      run: |
        python -m pip install --upgrade pip
        pip install md2pdf

    - name: Delete old PDFs
      run: |
        if [ -d "pdf" ]; then
          rm -rf pdf
        fi

    - name: Generate new PDFs
      run: |
        find . -name "*.md" | while IFS= read -r md_file; do
          md_file="${md_file#./}"

          pdf_dir="pdf/$(dirname "$md_file")"
          pdf_file="$pdf_dir/$(basename "$md_file" .md).pdf"

          echo "Creating directory $pdf_dir"
          echo "Filename is $pdf_file"
          mkdir -p "$pdf_dir"
          md2pdf "$md_file" "$pdf_file"
        done

    - name: Push to repo
      run: |
        git config --global user.email "kristian.zh.apostolov@gmail.com"
        git config --global user.name "Kristian Apostolov"
        git add pdf/*
        git commit -m "Generate PDFs"
        git push origin main

